# Generated by Django 2.2.7 on 2020-01-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('books', '0006_auto_20200102_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Позиция в книге')),
                ('date', models.DateField(verbose_name='Дата добавления')),
                ('book_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Добавленная закладка',
                'verbose_name_plural': 'Добавленные закладки',
            },
        ),
    ]
