# Generated by Django 2.2.7 on 2020-01-02 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='book_id',
            new_name='book',
        ),
    ]
