# Generated by Django 2.2.7 on 2020-01-02 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0006_auto_20200102_1648'),
        ('bookmarks', '0002_auto_20200102_1718'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('book', 'position')},
        ),
    ]
