# Generated by Django 2.2.7 on 2019-11-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cur_page',
            new_name='current',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Всего страниц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='filename',
            field=models.CharField(default=1, max_length=50, verbose_name='Название файла'),
            preserve_default=False,
        ),
    ]
