# Generated by Django 2.2.7 on 2019-11-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191130_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_size',
            field=models.IntegerField(default=12, verbose_name='Размер страницы'),
            preserve_default=False,
        ),
    ]
