# Generated by Django 2.2.7 on 2019-12-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_page_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='local_file',
            field=models.CharField(default=1, max_length=50, verbose_name='Файл на сервере'),
            preserve_default=False,
        ),
    ]
