# Generated by Django 2.2.7 on 2020-01-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_local_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page_size',
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(verbose_name='Всего слов'),
        ),
        migrations.AlterField(
            model_name='book',
            name='current',
            field=models.IntegerField(verbose_name='Текущая позиция (слово)'),
        ),
    ]
