# Generated by Django 2.2.7 on 2020-01-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200102_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='filename',
            field=models.CharField(max_length=50, verbose_name='Название книги'),
        ),
    ]
