# Generated by Django 2.2.7 on 2019-12-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateWord',
            fields=[
                ('word', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Слово')),
                ('translate', models.CharField(max_length=15, verbose_name='Перевод')),
                ('frequency', models.IntegerField(verbose_name='Частота')),
            ],
            options={
                'verbose_name': 'Переведенное слово',
                'verbose_name_plural': 'Переведенные слова',
            },
        ),
    ]
